version: '3.9'

services:
  dbserver:
    image: postgres:13.3
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: db
        POSTGRES_USER: app
        POSTGRES_PASSWORD: app
  